# Generated by Django 5.1.6 on 2025-03-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Katgoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Yengililar'},
        ),
    ]
