# Generated by Django 5.1.6 on 2025-03-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contactmodel_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time'], 'verbose_name_plural': 'News'},
        ),
    ]
